<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Views\Resources\Fonts\CormorantGaramond-VariableFont.ttf" />
    <Resource Include="Views\Resources\Fonts\CormorantGaramond-VariableFont.ttf" />
    <None Remove="Views\Resources\Images\EldenRing.png" />
    <Resource Include="Views\Resources\Images\EldenRing.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Caliburn.Micro" Version="5.0.258" />
    <PackageReference Include="Grace" Version="7.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\ShellView.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>
